### ISSUE TITLE
missing sauth

### ISSUE THREAD

**Issue by ArnoldAgema** [Hostle/openwrt-luci-multi-user#1]
/usr/lib/lua/luci/controller/admin/users.lua:5: module 'luci.sauth' not found:
    no field package.preload['luci.sauth']
    no file './luci/sauth.lua'
    no file '/usr/share/lua/luci/sauth.lua'
    no file '/usr/share/lua/luci/sauth/init.lua'
    no file '/usr/lib/lua/luci/sauth.lua'
    no file '/usr/lib/lua/luci/sauth/init.lua'
    no file './luci/sauth.so'
    no file '/usr/lib/lua/luci/sauth.so'
    no file '/usr/lib/lua/loadall.so'
    no file './luci.so'
    no file '/usr/lib/lua/luci.so'
    no file '/usr/lib/lua/loadall.so'
stack traceback:
    [C]: in function 'require'
    /usr/lib/lua/luci/controller/admin/users.lua:5: in function 't'
    /usr/lib/lua/luci/dispatcher.lua:517: in function 'createtree'
    /usr/lib/lua/luci/dispatcher.lua:163: in function 'dispatch'
    /usr/lib/lua/luci/dispatcher.lua:138: in function </usr/lib/lua/luci/dispatcher.lua:137>

**Comment by Hostle** [comment]
luci.sauth is part of the luci. To manually apply the multi-user code in this repo you would first install openwrt luci and manually add the files over top of the originals, then reboot or remove "/tmp/luci-indexcache .

**Comment by ArnoldAgema** [comment]
Applied it to the trunk en rebuild it from the source. After firmware upgrade this error occurred. Where should i put the source files? feeds/luci???

**Comment by Hostle** [comment]
This project is on going and not yet ready for release, this is why the src is incomplete. You an apply it manually and test it at your own risk but i would suggest you wait until it is completed. With that said, if you would still like to try it I would suggest you create a directory called "files" in the top level of you src, then add the directories and files there. this way the files will be installed automatically post build..

ie ..top level is the main directory of the src, if using trunk the top level should be the "trunk" directory
create the "files" directory and add the following directories and files 

 files/ usr/ lib/ lua /luci / "dispatcher.lua" , "users.lua"
 files/ usr/ lib/ lua /luci /controller/admin/ "serviectl.lua", "index.lua", "users.lua"
 files/ usr/ lib/ lua /luci/ model/cbi/admin_users/ "passwd.lua", "users.lua"

then rebuild

**Comment by ArnoldAgema** [comment]
Did this. Still the same error.

**Comment by Hostle** [comment]
It appears that luci.sauth is no longer included in luci, see here for details https://github.com/Hostle/openwrt-luci/commit/199c8cbc4c32506ecfe89850615b88a3f0276dd3

I have made changes to the src, try it now with the new src and let me know if it works for you

**Comment by Hostle** [comment]
ok i finally had a chance to test it against the trunk,  I had to make a few changes to accommodate the changes made to luci. I can confirm it is now working and fully functional with latest snapshot (OpenWrt Chaos Calmer r44379 / LuCI (git-15.041.27918-86c6272) .

**Comment by ArnoldAgema** [comment]
The install is still unclear to me. How do i get this into my own build? @Hostle

**Comment by Hostle** [comment]
just add the appropriate feed from below to your "feeds.conf.default" and comment out the original luci feed ( put a "#" in front of the original luci feed) and then update the new luci feed

./scripts/feeds update luci
./scripts/feeds install -a -p luci

then you should see the new pkg in the menuconfig under LuCI >> Modules > admin-multi-user

## LuCI 0.12 / 14.07 Barrier Breaker Branch  feed

src-git luci https://github.com/Hostle/openwrt-luci-multi-user.git;luci-0.12

or the development branch (trunk)

## LuCI trunk / Chaos Calmer Branch  feed

src-git luci https://github.com/Hostle/openwrt-luci-multi-user.git

**Comment by ArnoldAgema** [comment]
did a new compile with the new source. In Luci I get this:

/usr/lib/lua/luci/dispatcher.lua:526: Failed to execute cbi dispatcher target for entry '/admin/users/users'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:311: Unable to read UCI data: users
stack traceback:
    [C]: in function 'assert'
    /usr/lib/lua/luci/dispatcher.lua:526: in function 'dispatch'
    /usr/lib/lua/luci/dispatcher.lua:182: in function </usr/lib/lua/luci/dispatcher.lua:181>

@Hostle 
Something missing? users are created.

**Comment by Hostle** [comment]
add a blank file "/etc/config/users" and reboot router
