### ISSUE TITLE
error after install luci-mod-admin-multi-user

### ISSUE THREAD

**Issue by ivan1369** [Hostle/openwrt-luci-multi-user#2]
/usr/lib/lua/luci/controller/admin/users.lua:27: attempt to call field 'get_user' (a nil value)
stack traceback:
    /usr/lib/lua/luci/controller/admin/users.lua:27: in function 'v'
    /usr/lib/lua/luci/dispatcher.lua:649: in function 'createtree'
    /usr/lib/lua/luci/dispatcher.lua:215: in function 'dispatch'
    /usr/lib/lua/luci/dispatcher.lua:182: in function </usr/lib/lua/luci/dispatcher.lua:181>

in router tp-link wr740n v5 trunk

If I uninstall the package (opkg remove luci-mod-admin-multi-user), everything works

**Comment by Hostle** [comment]
what version are you using ?

**Comment by Hostle** [comment]
just add the appropriate feed to your "feeds.conf.default" and then put a "#" in front of the original luci feed and then update the luci feed

## LuCI 0.12 / 14.07 Barrier Breaker Branch

src-git luci https://github.com/Hostle/openwrt-luci-multi-user.git;luci-0.12

or the development branch

## LuCI trunk / Chaos Calmer Branch

src-git luci https://github.com/Hostle/openwrt-luci-multi-user.git

**Comment by ivan1369** [comment]
I use openwrt trunk 

LuCI trunk / Chaos Calmer Branch

src-git luci https://github.com/Hostle/openwrt-luci-multi-user.git

compiles correctly but when entering 192.168.1.1 get the error

tplink wr740 v5 only work whit openwrt trunk

**Comment by Hostle** [comment]
Ok, I will try and duplicate the error. Thank you for testing the code and reporting the issue. I will get it fixed up

**Comment by Hostle** [comment]
I duplicated the error and located the problem. The get_users() function was not in the scope of the users.lua controller. I have fixed it and edited the src. I fresh build work like a charm. Please confirm so I can close the ticket.

**Comment by ivan1369** [comment]
when creating a user and hit save and apply get this error

/usr/lib/lua/luci/dispatcher.lua:550: Failed to execute cbi dispatcher target for entry '/admin/users/users'.
The called action terminated with an exception:
/usr/lib/lua/luci/users.lua:145: table index is nil
stack traceback:
    [C]: in function 'assert'
    /usr/lib/lua/luci/dispatcher.lua:550: in function 'dispatch'
    /usr/lib/lua/luci/dispatcher.lua:198: in function </usr/lib/lua/luci/dispatcher.lua:197>

**Comment by Hostle** [comment]
can you manually clear the contents of /etc/config/users and try again. Just ssh into the router and do something like ...  echo  > /etc/config/users or use winscp to clear the contents and save it

**Comment by ivan1369** [comment]
ok
I created the user " Ivan " , and what is the password?

**Comment by Hostle** [comment]
the default password is set to simply "openwrt". Once the user logs in they can set the password to whatever they like. I updated the readme with this information

**Comment by Hostle** [comment]
I am just adding in support to hide the main sub tabs :)

**Comment by ivan1369** [comment]
Work fine :)
thank very much

you have PayPal for a small donation?

**Comment by Hostle** [comment]
donation is not mandatory but my paypal is hos-style@hotmail.com :) thanks for your generosity. Also thanks for your participation in testing.
