### ISSUE TITLE
Add interface error

### ISSUE THREAD

**Issue by ArnoldAgema** [Hostle/openwrt-luci-multi-user#3]
Hello,

Added a interface for umts 3g with luci protocol proto-3g and received the following error

No page is registered at '/admin/network/network/3G'.
If this url belongs to an extension, make sure it is properly installed.
If the extension was recently installed, try removing the /tmp/luci-indexcache file.

**Comment by Hostle** [comment]
I can not reproduce the error. Can you provide a list of installed luci packages and describe the steps to receive the error

**Comment by Hostle** [comment]
ok i manage to track down the error, it was just a simply path was incorrect. I have corrected both branches and this should no longer be an issue. I am now closing this issue
